# Generated by Django 4.0.5 on 2022-06-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50)),
                ('company', models.CharField(default=None, max_length=50)),
                ('salary', models.IntegerField(default=None)),
                ('still_open', models.BooleanField(default=True)),
                ('description', models.TextField(default=None)),
            ],
        ),
    ]
