# Generated by Django 4.0.5 on 2022-06-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
