# Generated by Django 4.0.5 on 2022-06-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='location',
            new_name='job_location',
        ),
    ]
