# Generated by Django 4.0.5 on 2022-06-16 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='display_message',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='job',
            name='logo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='job',
            name='website',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
