# Generated by Django 4.0.5 on 2022-06-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='display_message',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
