# Generated by Django 4.0.5 on 2022-06-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(blank=True, default='http://romanroadtrust.co.uk/wp-content/uploads/2018/01/profile-icon-png-898.png', max_length=300),
        ),
    ]
