# Generated by Django 4.0.5 on 2022-06-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0004_alter_application_job_alter_application_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applied',
            field=models.BooleanField(default=True),
        ),
    ]
